const stops=[
{name:"Hess Recreation Area",place:"Danville, PA",address:"843 Meadow Ln, Danville, PA 17821",time:"~2h 25m",detour:"+6 min",match:94,minutes:26,tags:["🌱 115-acre recreation area","🐕 Leashed dogs permitted","🚻 Year-round restrooms","🚗 Parking"],why:"Large public recreation area with fields and trails, while avoiding a concentrated highway pet-relief area.",confidence:"High",provenance:"Official MARC park page + official park rules",source:"https://montourrec.com/hess-fields/",caveat:"Dog traffic and current grass condition are not yet verified by Pawstop users."},
{name:"Brandy Springs Park",place:"Mercer, PA",address:"197 William T Wardle Dr, Mercer, PA 16137",time:"~4h 55m",detour:"+7 min",match:84,minutes:31,tags:["🌱 Community park","🚗 Parking","🐕 Dog facilities on site","🧺 Recreation space"],why:"A substantial community park near the corridor. Because it includes a dedicated dog park, Pawstop flags this as a lower-confidence puppy option rather than assuming all lawn areas are appropriate.",confidence:"Medium",provenance:"Official park site + current place data",source:"https://www.brandyspringspark.com/",caveat:"Field verification of pet access outside the dedicated dog park is still needed."},
{name:"Mill Creek Park",place:"Youngstown, OH",address:"1001 Canfield Rd, Youngstown, OH 44511",time:"~7h 15m",detour:"+7 min",match:90,minutes:24,tags:["🌳 Large park system","🐕 Leashed pets on trails + drives","🚗 Parking","🥾 Walking options"],why:"A large park system where leashed pets are explicitly permitted on trails and drives, offering more room than a highway relief area.",confidence:"High",provenance:"Official Mill Creek MetroParks rules + park information",source:"https://www.millcreekmetroparks.org/park-rules-regulations/",caveat:"Pets are not permitted in picnic, recreation, or garden areas; routing should target a pet-permitted access point."},
{name:"Wildwood Preserve Metropark",place:"Toledo, OH",address:"5100 W Central Ave, Toledo, OH 43615",time:"~9h 35m",detour:"+6 min",match:93,minutes:29,tags:["🌱 493-acre preserve","🐕 Dogs welcome on leash","🚗 Designated parking","🥾 Trails"],why:"Large preserve with extensive outdoor space. Metroparks Toledo explicitly welcomes leashed dogs in Wildwood.",confidence:"High",provenance:"Official Metroparks Toledo Wildwood page + park rules",source:"https://metroparkstoledo.com/wildwoodpreserve",caveat:"Open 7 a.m. to dark. Current dog traffic and grass condition need community verification."},
{name:"St. Patrick's County Park",place:"South Bend, IN",address:"50651 Laurel Rd, South Bend, IN 46637",time:"~11h 40m",detour:"+7 min",match:91,minutes:33,tags:["🌳 398 acres","🐕 Leashed dogs documented","🚻 Restrooms","🚗 Parking"],why:"Large county park with trails and practical traveler amenities. Current county programming explicitly welcomes dogs on a physical 6-foot leash.",confidence:"High",provenance:"Official St. Joseph County park + facilities + 2026 dog-event pages",source:"https://www.sjcparks.org/592/St-Patricks-County-Park",caveat:"Hours and possible seasonal vehicle fees should be checked at trip time."}
];
const alternatives={fastest:{...stops[0],name:"I-80 Highway Rest Area",place:"Danville area, PA",address:"I-80 Rest Area, Danville, PA",match:76,minutes:14,detour:"+0 min",tags:["↪ Direct highway access","🚻 Restrooms","🐕 Pet area"],why:"Fastest option with essentially no route detour, but it does not match your preference to avoid concentrated pet-relief areas.",confidence:"Medium",provenance:"Public highway/rest-area information",source:"https://www.pa.gov/agencies/penndot",caveat:"Dog traffic and pet-area condition are unknown."},grass:stops[0],restrooms:{...stops[3],minutes:38,match:91,why:"A strong alternative when you prioritize a large park plus established visitor facilities and parking."}};
const $=id=>document.getElementById(id); document.querySelectorAll(".chip").forEach(x=>x.onclick=()=>x.classList.toggle("active"));
function navUrl(s){return "https://www.google.com/maps/dir/?api=1&destination="+encodeURIComponent(s.address)}
function prov(s){return `<strong>${s.confidence} confidence</strong><br>${s.provenance}<br><a class="source-link" href="${s.source}" target="_blank" rel="noopener">View source ↗</a>`}
function renderStops(){$("stops").innerHTML=stops.map((s,i)=>`<article class="stop"><div class="stop-head"><div><h3>${i+1}. ${s.name}</h3><p class="place">${s.place}</p></div><span class="match">${s.match}% MATCH</span></div><p class="meta">${s.time} into trip · ${s.detour} detour</p><div class="tags">${s.tags.map(t=>`<span>${t}</span>`).join("")}</div><div class="stop-actions"><button onclick="showWhy(${i})">Why this stop?</button><button onclick="window.open('${navUrl(s)}','_blank')">Navigate ↗</button></div><div id="why-${i}" class="data-note hidden">${s.why}<br><br>${prov(s)}</div></article>`).join("")}
window.showWhy=i=>document.getElementById("why-"+i).classList.toggle("hidden");
$("planBtn").onclick=()=>{const dog=$("dog").value.trim()||"Your dog";$("routeFrom").textContent=$("from").value;$("routeTo").textContent=$("to").value;$("dogName").textContent=dog;$("profile").textContent=$("age").value+" · breaks every "+$("break").value;$("needText").textContent=dog+" needs a stop";renderStops();$("planner").classList.add("hidden");$("route").classList.remove("hidden");scrollTo(0,0)};
$("backBtn").onclick=()=>{$("route").classList.add("hidden");$("planner").classList.remove("hidden");scrollTo(0,0)};
let current=stops[0];function renderUrgent(s){current=s;$("urgentMatch").textContent=s.match+"% MATCH";$("urgentName").textContent=s.name;$("urgentPlace").textContent=s.place;$("urgentMinutes").textContent=s.minutes;$("urgentDetour").textContent=s.detour+" estimated detour";$("urgentFeatures").innerHTML=s.tags.map(t=>`<span>${t}</span>`).join("");$("urgentWhy").textContent=s.why;$("urgentConfidence").innerHTML=prov(s);$("urgentCaveat").textContent=s.caveat}
$("needStop").onclick=()=>{renderUrgent(stops[0]);$("route").classList.add("hidden");$("urgent").classList.remove("hidden");scrollTo(0,0)};$("urgentBack").onclick=()=>{$("urgent").classList.add("hidden");$("route").classList.remove("hidden");scrollTo(0,0)};$("navBtn").onclick=()=>window.open(navUrl(current),"_blank");document.querySelectorAll("[data-alt]").forEach(b=>b.onclick=()=>renderUrgent(alternatives[b.dataset.alt]));